import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'seedflow-language'

const translations = {
  nl: {
    common: {
      appName: 'Seedflow',
      loading: 'Laden...',
      cancel: 'Annuleren',
      delete: 'Verwijderen',
      edit: 'Bewerken',
      stage: 'Fase',
      noDate: 'Geen datum',
      role: {
        admin: 'Beheerder',
        manager: 'Manager',
        sales: 'Sales',
        user: 'Gebruiker',
      },
      languageShort: 'NL',
    },
    nav: {
      dashboard: 'Overzicht',
      pipeline: 'Pipeline',
      leads: 'Leads',
      calendar: 'Agenda',
      activities: 'Activiteit',
      proposals: 'Offertes',
    },
    login: {
      title: 'Log in op je CRM',
      email: 'E-mail',
      password: 'Wachtwoord',
      emailPlaceholder: 'jij@email.com',
      signIn: 'Inloggen',
      signingIn: 'Bezig met inloggen...',
      supabaseMissingTitle: 'Supabase niet geconfigureerd',
      supabaseMissingBody: 'Kopieer .env.example naar .env en vul je Supabase URL en anon key in. Herstart daarna de dev server.',
    },
    dashboard: {
      welcomeBack: 'Welkom terug, {name}',
      title: 'Overzicht',
      subtitle: 'Je sales pipeline in één oogopslag. Focus op high-intent leads en deadlines.',
      newLead: 'Nieuwe lead',
      newDeal: 'Nieuwe deal',
      totalPipelineValue: 'Totale pipeline waarde',
      allActiveDeals: 'Over alle actieve deals',
      conversion: 'Conversie',
      leads: 'Leads',
      activeDealsCount: '{count} actieve deals',
      upcoming: 'Binnenkort gepland',
      activeDeals: 'Actieve deals',
      viewPipeline: 'Bekijk pipeline',
      noDeals: 'Nog geen deals. Maak je eerste deal aan via de pipeline pagina.',
      tasks: 'Taken',
      noOpenTasks: 'Geen openstaande taken.',
      recentActivity: 'Recente activiteit',
      noActivities: 'Nog geen activiteiten.',
      noTaskDate: 'Geen datum',
      recentProposals: 'Recente offertes',
      proposalItems: 'regels',
      unknownLead: 'Onbekende lead',
    },
    admin: {
      accessDeniedTitle: 'Geen toegang',
      accessDeniedBody: 'Alleen admins hebben toegang tot deze pagina.',
      title: 'Gebruikersbeheer',
      subtitle: 'Maak CRM-gebruikers aan en beheer hun rollen.',
      addUser: 'Gebruiker toevoegen',
      newUser: 'Nieuwe gebruiker',
      fullName: 'Volledige naam *',
      email: 'E-mail *',
      password: 'Wachtwoord *',
      createUser: 'Gebruiker aanmaken',
      noName: 'Geen naam',
      noUsers: 'Geen gebruikers gevonden.',
      userCreated: 'Gebruiker {email} is aangemaakt.',
      roleUpdated: 'Gebruikersrol bijgewerkt.',
      userDeleted: 'Gebruiker verwijderd.',
      confirmDelete: 'Dit gebruikersprofiel verwijderen?',
    },
    leads: {
      statuses: {
        new_lead: 'Nieuwe lead',
        message_sent: 'Bericht gestuurd',
        no_response: 'Geen reactie',
        response_received: 'Reactie gekregen',
        meeting_planned: 'Gesprek gepland',
        meeting_done: 'Gesprek gehad',
        proposal_sent: 'Offerte gestuurd',
        won: 'Gewonnen',
        lost: 'Verloren',
        // legacy
        hot_lead: 'Warme lead',
        existing_client: 'Bestaande klant',
        nurturing: 'Opvolging',
        stale: 'Afgekoeld',
      },
      title: 'Leadoverzicht',
      subtitle: 'Beheer je relaties en volg de groei in je klantenpipeline.',
      search: 'Zoek op leads, bedrijven of tags...',
      importCsv: 'Import CSV',
      newLead: 'Nieuwe lead',
      allLeads: 'Alle leads',
      editLead: 'Lead bewerken',
      createLead: 'Nieuwe lead',
      fullName: 'Volledige naam *',
      company: 'Bedrijf',
      email: 'E-mail',
      phone: 'Telefoon',
      location: 'Locatie',
      updateLead: 'Lead bijwerken',
      createLeadButton: 'Lead aanmaken',
      noLeads: 'Geen leads gevonden.',
      noCompany: 'Geen bedrijf',
      newDeal: 'Nieuwe deal',
      edit: 'Bewerken',
      delete: 'Verwijderen',
      confirmDelete: 'Deze lead verwijderen?',
      importError: 'Importfout: {message}',
      importSuccess: '{count} leads geïmporteerd!',
      detail: {
        backToLeads: 'Leads',
        progress: 'Voortgang',
        addNote: 'Notitie toevoegen',
        notePlaceholder: 'Noteer hier bijv. wat de website mist, verbeterpunten of gesprekspunten...',
        postNote: 'Notitie plaatsen',
        notes: 'Notities',
        noNotes: 'Nog geen notities.',
        lostReason: 'Reden van verlies',
        lostReasonPlaceholder: 'Waarom wilde de klant niet? Noteer redenen om te optimaliseren...',
        save: 'Opslaan',
        proposalTimer: 'Offerte timer',
        timerRemaining: 'Resterende tijd om de offerte te versturen',
        timerExpired: 'De 1,5 uur om de offerte te sturen zijn verstreken.',
        timerExpiredLabel: 'Verlopen!',
        details: 'Details',
        noContact: 'Geen bedrijf',
        created: 'Aangemaakt',
        lostReasonLabel: 'Reden verlies',
        scheduleMeeting: 'Afspraak plannen',
        meetingType: 'Type afspraak',
        meetingZoom: 'Zoom meeting',
        meetingInPerson: 'Persoonlijke afspraak',
        meetingDate: 'Datum',
        meetingTime: 'Tijd',
        meetingUrl: 'Zoom link (optioneel)',
        meetingSubmit: 'Afspraak inplannen',
        websiteUrl: 'Website URL',
        closedAt: 'Afgesloten op',
        closedAtLabel: 'Afgesloten',
      },
    },
    pipeline: {
      titleEyebrow: 'Salesoverzicht',
      title: 'Actieve pipeline',
      newLead: 'Nieuwe lead',
      noCompany: 'Geen bedrijf',
      noLeads: 'Geen leads in deze fase',
      totalLeads: 'Totaal leads',
      activeLeads: 'Actieve leads',
      wonLeads: 'Gewonnen',
      openProposalValue: 'Open offertes',
      reopen: 'Heropenen',
    },
    dealDetail: {
      lead: 'Lead',
      unknown: 'Onbekend',
      editing: 'Deal bewerken',
      dealTitle: 'Dealtitel',
      company: 'Bedrijf',
      contactName: 'Contactnaam',
      contactEmail: 'E-mail contact',
      contactPhone: 'Telefoon contact',
      value: 'Waarde (€)',
      saveChanges: 'Wijzigingen opslaan',
      dealValue: 'Dealwaarde',
      closingDate: 'Sluitingsdatum',
      closingDateUnknown: 'Nog niet bekend',
      probability: 'Kans',
      addNote: 'Notitie toevoegen',
      notePlaceholder: 'Typ iets over deze deal...',
      postNote: 'Notitie plaatsen',
      notesTimeline: 'Notities & tijdlijn',
      noNotes: 'Nog geen notities.',
      contactPerson: 'Contactpersoon',
      noContact: 'Geen contactpersoon',
      internalDetails: 'Interne gegevens',
      created: 'Aangemaakt',
      confirmDelete: 'Deze deal en alle notities verwijderen?',
      stages: {
        lead: 'Lead',
        qualified: 'Gekwalificeerd',
        proposal: 'Voorstel',
        negotiation: 'Onderhandeling',
        closed_won: 'Gewonnen',
        closed_lost: 'Verloren',
      },
    },
    activities: {
      title: 'Activiteiten',
      subtitle: 'Beheer je groeisysteem voor vandaag.',
      newEvent: 'Nieuwe afspraak',
      noActivities: 'Geen activiteiten.',
      noTime: 'Geen tijd',
      untitled: 'Activiteit zonder titel',
      description: 'Beschrijving *',
      noLinkedLead: 'Geen gekoppelde lead',
      create: 'Aanmaken',
      today: 'Vandaag',
      upcoming: 'Komend',
      past: 'Afgelopen',
      types: {
        call: 'gesprek',
        email: 'e-mail',
        meeting: 'afspraak',
        note: 'notitie',
        deadline: 'deadline',
      },
    },
    calendar: {
      title: 'Agenda',
      newEvent: 'Nieuwe afspraak',
      thisMonth: 'Deze maand',
      meetings: 'Afspraken',
      calls: 'Gesprekken',
      deadlines: 'Deadlines',
      weekdaysShort: ['Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za', 'Zo'],
      description: 'Beschrijving *',
      noLinkedLead: 'Geen gekoppelde lead',
      add: 'Toevoegen',
      noActivities: 'Geen activiteiten op deze dag.',
      addEvent: '+ Voeg afspraak toe',
    },
    proposal: {
      eyebrow: 'Offerte opstellen',
      title: 'Offerte',
      backToLead: 'Terug naar lead',
      from: 'Van',
      to: 'Aan',
      yourDetails: 'Jouw bedrijfsgegevens',
      items: 'Wat bied je aan?',
      itemPlaceholder: 'Bijv. Website redesign, SEO pakket, Logo ontwerp...',
      addItem: 'Regel toevoegen',
      subtotal: 'Subtotaal',
      vat: 'BTW',
      total: 'Totaal',
      notesLabel: 'Opmerkingen',
      notesPlaceholder: 'Bijv. betalingsvoorwaarden, levertijd, extra afspraken...',
      validity: 'Geldigheid',
      days: 'dagen',
      validUntil: 'Geldig tot',
      send: 'Offerte versturen',
      sending: 'Versturen...',
      sent: 'Offerte verstuurd!',
    },
    proposals: {
      title: 'Offertes',
      subtitle: 'Bekijk, bewerk en beheer al je verstuurde offertes.',
      noProposals: 'Nog geen offertes verstuurd.',
      unknownLead: 'Onbekende lead',
      statusOpen: 'Open',
      statusWon: 'Gewonnen',
      statusLost: 'Verloren',
      statusExpired: 'Verlopen',
      edit: 'Bewerken',
      delete: 'Verwijderen',
      confirmDelete: 'Deze offerte verwijderen?',
      save: 'Opslaan',
      addItem: 'Regel toevoegen',
      itemPlaceholder: 'Bijv. Website redesign, SEO pakket...',
      notesPlaceholder: 'Opmerkingen...',
      subtotalLabel: 'Subtotaal',
      vatLabel: 'BTW',
      totalLabel: 'Totaal',
      validUntilLabel: 'Geldig tot',
      validityLabel: 'Geldigheid',
      daysLabel: 'dagen',
    },
  },
  en: {
    common: {
      appName: 'Seedflow',
      loading: 'Loading...',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      stage: 'Stage',
      noDate: 'No date',
      role: {
        admin: 'Admin',
        manager: 'Manager',
        sales: 'Sales',
        user: 'User',
      },
      languageShort: 'EN',
    },
    nav: {
      dashboard: 'Home',
      pipeline: 'Pipeline',
      leads: 'Leads',
      calendar: 'Calendar',
      activities: 'Activity',
      proposals: 'Proposals',
    },
    login: {
      title: 'Sign in to your CRM',
      email: 'Email',
      password: 'Password',
      emailPlaceholder: 'you@email.com',
      signIn: 'Sign In',
      signingIn: 'Signing in...',
      supabaseMissingTitle: 'Supabase not configured',
      supabaseMissingBody: 'Copy .env.example to .env and fill in your Supabase URL and anon key. Restart the dev server afterwards.',
    },
    dashboard: {
      welcomeBack: 'Welcome back, {name}',
      title: 'Overview',
      subtitle: 'Your sales pipeline at a glance. Focus on high-intent leads and deadlines.',
      newLead: 'New Lead',
      newDeal: 'New Deal',
      totalPipelineValue: 'Total Pipeline Value',
      allActiveDeals: 'Across all active deals',
      conversion: 'Conversion',
      leads: 'Leads',
      activeDealsCount: '{count} active deals',
      upcoming: 'Coming up',
      activeDeals: 'Active Deals',
      viewPipeline: 'View Pipeline',
      noDeals: 'No deals yet. Create your first deal from the pipeline page.',
      tasks: 'Tasks',
      noOpenTasks: 'No open tasks.',
      recentActivity: 'Recent Activity',
      noActivities: 'No activities yet.',
      noTaskDate: 'No date',
      recentProposals: 'Recent Proposals',
      proposalItems: 'items',
      unknownLead: 'Unknown lead',
    },
    admin: {
      accessDeniedTitle: 'Access Denied',
      accessDeniedBody: 'Only admins can access this page.',
      title: 'User Management',
      subtitle: 'Create CRM users and manage their roles.',
      addUser: 'Add User',
      newUser: 'New User',
      fullName: 'Full Name *',
      email: 'Email *',
      password: 'Password *',
      createUser: 'Create User',
      noName: 'No name',
      noUsers: 'No users found.',
      userCreated: 'User {email} has been created.',
      roleUpdated: 'User role updated.',
      userDeleted: 'User deleted.',
      confirmDelete: 'Delete this user profile?',
    },
    leads: {
      statuses: {
        new_lead: 'New Lead',
        message_sent: 'Message Sent',
        no_response: 'No Response',
        response_received: 'Response Received',
        meeting_planned: 'Meeting Planned',
        meeting_done: 'Meeting Done',
        proposal_sent: 'Proposal Sent',
        won: 'Won',
        lost: 'Lost',
        // legacy
        hot_lead: 'Hot Lead',
        existing_client: 'Existing Client',
        nurturing: 'Nurturing',
        stale: 'Stale',
      },
      title: 'Lead Overview',
      subtitle: 'Manage your relationships and track growth across your client pipeline.',
      search: 'Search leads, companies or tags...',
      importCsv: 'Import CSV',
      newLead: 'New Lead',
      allLeads: 'All Leads',
      editLead: 'Edit Lead',
      createLead: 'New Lead',
      fullName: 'Full Name *',
      company: 'Company',
      email: 'Email',
      phone: 'Phone',
      location: 'Location',
      updateLead: 'Update Lead',
      createLeadButton: 'Create Lead',
      noLeads: 'No leads found.',
      noCompany: 'No company',
      newDeal: 'New Deal',
      edit: 'Edit',
      delete: 'Delete',
      confirmDelete: 'Delete this lead?',
      importError: 'Import error: {message}',
      importSuccess: '{count} leads imported!',
      detail: {
        backToLeads: 'Leads',
        progress: 'Progress',
        addNote: 'Add Note',
        notePlaceholder: 'Note website issues, improvement points or talking points...',
        postNote: 'Post Note',
        notes: 'Notes',
        noNotes: 'No notes yet.',
        lostReason: 'Reason for Loss',
        lostReasonPlaceholder: 'Why did the client say no? Note reasons to optimize...',
        save: 'Save',
        proposalTimer: 'Proposal Timer',
        timerRemaining: 'Time remaining to send the proposal',
        timerExpired: 'The 1.5 hour window to send the proposal has passed.',
        timerExpiredLabel: 'Expired!',
        details: 'Details',
        noContact: 'No company',
        created: 'Created',
        lostReasonLabel: 'Loss reason',
        scheduleMeeting: 'Schedule Meeting',
        meetingType: 'Meeting Type',
        meetingZoom: 'Zoom meeting',
        meetingInPerson: 'In-person meeting',
        meetingDate: 'Date',
        meetingTime: 'Time',
        meetingUrl: 'Zoom link (optional)',
        meetingSubmit: 'Schedule Meeting',
        websiteUrl: 'Website URL',
        closedAt: 'Closed on',
        closedAtLabel: 'Closed',
      },
    },
    pipeline: {
      titleEyebrow: 'Sales Overview',
      title: 'Active Pipeline',
      newLead: 'New Lead',
      noCompany: 'No company',
      noLeads: 'No leads in this stage',
      totalLeads: 'Total Leads',
      activeLeads: 'Active Leads',
      wonLeads: 'Won',
      openProposalValue: 'Open Proposals',
      reopen: 'Reopen',
    },
    dealDetail: {
      lead: 'Lead',
      unknown: 'Unknown',
      editing: 'Editing Deal',
      dealTitle: 'Deal Title',
      company: 'Company',
      contactName: 'Contact Name',
      contactEmail: 'Contact Email',
      contactPhone: 'Contact Phone',
      value: 'Value (€)',
      saveChanges: 'Save Changes',
      dealValue: 'Deal Value',
      closingDate: 'Closing Date',
      closingDateUnknown: 'TBD',
      probability: 'Probability',
      addNote: 'Add Note',
      notePlaceholder: 'Type something about this deal...',
      postNote: 'Post Note',
      notesTimeline: 'Notes & Timeline',
      noNotes: 'No notes yet.',
      contactPerson: 'Contact Person',
      noContact: 'No contact',
      internalDetails: 'Internal Details',
      created: 'Created',
      confirmDelete: 'Delete this deal and all notes?',
      stages: {
        lead: 'Lead',
        qualified: 'Qualified',
        proposal: 'Proposal',
        negotiation: 'Negotiation',
        closed_won: 'Won',
        closed_lost: 'Lost',
      },
    },
    activities: {
      title: 'Activities',
      subtitle: 'Manage your growth system for today.',
      newEvent: 'New Event',
      noActivities: 'No activities.',
      noTime: 'No time',
      untitled: 'Untitled activity',
      description: 'Description *',
      noLinkedLead: 'No linked lead',
      create: 'Create',
      today: 'Today',
      upcoming: 'Upcoming',
      past: 'Past',
      types: {
        call: 'call',
        email: 'email',
        meeting: 'meeting',
        note: 'note',
        deadline: 'deadline',
      },
    },
    calendar: {
      title: 'Calendar',
      newEvent: 'New Event',
      thisMonth: 'This Month',
      meetings: 'Meetings',
      calls: 'Calls',
      deadlines: 'Deadlines',
      weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      description: 'Description *',
      noLinkedLead: 'No linked lead',
      add: 'Add',
      noActivities: 'No activities on this day.',
      addEvent: '+ Add event',
    },
    proposal: {
      eyebrow: 'Create proposal',
      title: 'Proposal',
      backToLead: 'Back to lead',
      from: 'From',
      to: 'To',
      yourDetails: 'Your company details',
      items: 'What are you offering?',
      itemPlaceholder: 'E.g. Website redesign, SEO package, Logo design...',
      addItem: 'Add line item',
      subtotal: 'Subtotal',
      vat: 'VAT',
      total: 'Total',
      notesLabel: 'Notes',
      notesPlaceholder: 'E.g. payment terms, delivery time, additional agreements...',
      validity: 'Validity',
      days: 'days',
      validUntil: 'Valid until',
      send: 'Send proposal',
      sending: 'Sending...',
      sent: 'Proposal sent!',
    },
    proposals: {
      title: 'Proposals',
      subtitle: 'View, edit and manage all your sent proposals.',
      noProposals: 'No proposals sent yet.',
      unknownLead: 'Unknown lead',
      statusOpen: 'Open',
      statusWon: 'Won',
      statusLost: 'Lost',
      statusExpired: 'Expired',
      edit: 'Edit',
      delete: 'Delete',
      confirmDelete: 'Delete this proposal?',
      save: 'Save',
      addItem: 'Add line item',
      itemPlaceholder: 'E.g. Website redesign, SEO package...',
      notesPlaceholder: 'Notes...',
      subtotalLabel: 'Subtotal',
      vatLabel: 'VAT',
      totalLabel: 'Total',
      validUntilLabel: 'Valid until',
      validityLabel: 'Validity',
      daysLabel: 'days',
    },
  },
}

const LanguageContext = createContext({})

function getValue(obj, path) {
  return path.split('.').reduce((acc, key) => acc?.[key], obj)
}

function interpolate(value, params) {
  if (typeof value !== 'string') return value
  return value.replace(/\{(\w+)\}/g, (_, key) => params?.[key] ?? '')
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem(STORAGE_KEY) || 'nl'
  })

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
  }, [language])

  const value = useMemo(() => {
    const locale = language === 'nl' ? 'nl-NL' : 'en-US'
    return {
      language,
      locale,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === 'nl' ? 'en' : 'nl')),
      t: (path, params) => {
        const result = getValue(translations[language], path)
        return interpolate(result ?? path, params)
      },
    }
  }, [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}
